// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var State = require("./State.bs.js");
var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReasonUnstated = require("../src/reasonUnstated.bs.js");

function useCounter(initial) {
  var match = React.useState((function () {
          return initial;
        }));
  var set = match[1];
  return /* record */[
          /* count */match[0],
          /* set */set,
          /* inc */(function (param) {
              return Curry._1(set, (function (prev) {
                            return prev + 1 | 0;
                          }));
            }),
          /* dec */(function (param) {
              return Curry._1(set, (function (prev) {
                            return prev - 1 | 0;
                          }));
            })
        ];
}

var CounterContainer = ReasonUnstated.MakeContainer(/* module */[/* useHook */useCounter]);

function Index$CounterDisplay(Props) {
  var counter = Curry._1(CounterContainer[/* useContainer */1], /* () */0);
  return React.createElement("div", undefined, "count: ", String(counter[/* count */0]), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(counter[/* inc */2], /* () */0);
                    })
                }, "+1"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(counter[/* dec */3], /* () */0);
                    })
                }, "-1"));
}

var CounterDisplay = /* module */[/* make */Index$CounterDisplay];

ReactDOMRe.renderToElementWithId(React.createElement("div", undefined, React.createElement(CounterContainer[/* Provider */0][/* make */1], {
              initialState: 0,
              children: null
            }, React.createElement(Index$CounterDisplay, { }), React.createElement(Index$CounterDisplay, { }), React.createElement(CounterContainer[/* Provider */0][/* make */1], {
                  initialState: 3,
                  children: null
                }, React.createElement(Index$CounterDisplay, { }), React.createElement(Index$CounterDisplay, { }))), React.createElement(State.StateContainer[/* Provider */0][/* make */1], {
              initialState: "hello",
              children: null
            }, React.createElement(State.StateDisplay[/* make */0], { }), React.createElement(State.StateDisplay[/* make */0], { }))), "app");

exports.useCounter = useCounter;
exports.CounterContainer = CounterContainer;
exports.CounterDisplay = CounterDisplay;
/* CounterContainer Not a pure module */
