// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonUnstated = require("../src/reasonUnstated.bs.js");

function useHook(initial) {
  return React.useState((function () {
                return initial;
              }));
}

var StateContainer = ReasonUnstated.MakeContainer(/* module */[/* useHook */useHook]);

function State$StateDisplay(Props) {
  var match = Curry._1(StateContainer[/* useContainer */1], /* () */0);
  var set = match[1];
  return React.createElement("div", {
              onClick: (function (param) {
                  return Curry._1(set, (function (prev) {
                                return prev + "s";
                              }));
                })
            }, match[0]);
}

var StateDisplay = /* module */[/* make */State$StateDisplay];

exports.StateContainer = StateContainer;
exports.StateDisplay = StateDisplay;
/* StateContainer Not a pure module */
