// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function useCounter(initial) {
  var match = React.useState((function () {
          return initial;
        }));
  var set = match[1];
  return /* record */[
          /* count */match[0],
          /* set */set,
          /* inc */(function (param) {
              return Curry._1(set, (function (prev) {
                            return prev + 1 | 0;
                          }));
            }),
          /* dec */(function (param) {
              return Curry._1(set, (function (prev) {
                            return prev - 1 | 0;
                          }));
            })
        ];
}

exports.useCounter = useCounter;
/* react Not a pure module */
